import PageHero from '@/components/heros/PageHero'
import Services from '@/components/Services'
export const metadata = {
  title: 'Finb Services',
  description: 'Generated by StaticMania',
}
export default function ServicePage() {
  return (
    <>
      <PageHero
        subtitle="OUR SERVICES"
        title="The world’s best companies <br> trust Finb "
        paragraph=""
      />
      <Services sectionDetails={false} />
    </>
  )
}
